apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: adequate-magpie-go 
  janus-idp.io/tekton: adequate-magpie-go
  backstage.io/kubernetes-id: adequate-magpie-go
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: adequate-magpie-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  